### ISSUE TITLE
Additional information in the left sidebar

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#59]
I would like to see in the left side menu, the file name and its serial number to the total number of files. Example:   
Bla-bla.png 43/120.
Without it, I really uncomfortable to view images.

**Comment by luspi** [comment]
Thanks for the suggestion!
Do you mean in addition to the quickinfo labels in the top right corners? This is actually a very trivial addition, I just added it to the code for the next release: abebe435858fe6c840796395a4f6d39caf950ec8

**Comment by KOT040188** [comment]
Вот это меню https://dl.dropboxusercontent.com/u/85152410/ss/ss_2016.11.08_18%3A16%3A40.png

**Comment by KOT040188** [comment]
Here is the menu https://dl.dropboxusercontent.com/u/85152410/ss/ss_2016.11.16_20%3A08%3A56.bmp

**Comment by luspi** [comment]
Alright, this will be the one in the next release (two added entries for filename and image number):
![New Metadata Entries](http://photoqt.org/newmetadataentries.jpg)

**Comment by KOT040188** [comment]
Thank you =)
