### ISSUE TITLE
Additional button in the right sidebar

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#60]
In the right side menu there is an item 'Exit'. But I would like to have a small exit button in the upper right corner of the sidebar.  It would be very convenient for me.

**Comment by luspi** [comment]
Although the mainmenu doesn't have its own button, the button that is shown in the upper right corner of the main screen (below the mainmenu) actually still works when clicked on even if the mainmenu is open...

**Comment by luspi** [comment]
Ha, I just realised that you might have hidden that element... I gave MainMenu its own exit button now: da02949f4016f7b95a7a39981c5852b85bdc4c5a

**Comment by KOT040188** [comment]
Yes, you understood me correctly =)

**Comment by KOT040188** [comment]
I do not want to overlap the image interface elements.

**Comment by luspi** [comment]
Alright, I can understand that (that's why there's an option to hide all of that) =)

**Comment by KOT040188** [comment]
Your link does not open. I can rely on the implementation of this button in the right sidebar?

**Comment by luspi** [comment]
Oh, it seems like GitLab is down at the moment... should be back soon!

[B]Edit:[/B] Yes it is down shortly: https://twitter.com/gitlabstatus

**Comment by KOT040188** [comment]
I can rely on the implementation of this button in the right sidebar?

**Comment by luspi** [comment]
You mean, that it is always there and working? Yes, it is always displayed with the main menu!

**Comment by KOT040188** [comment]
No. I'm talking about the button in the upper right corner. But not in the image, and the right-side menu. I do not want to close the image of the button.

**Comment by KOT040188** [comment]
I need like a button, but only in the right sidebar.

**Comment by KOT040188** [comment]
Maybe me hard to understand. I use google translator.

**Comment by luspi** [comment]
That's ok, it took me a long time, too, before I was able to really speak English (my native language is German). Before then I also used google translator a lot...
I guess you are talking about the sidebar that is used for the main menu, right? I added a button to that sidebar:
![new main menu](http://photoqt.org/newmainmenu.jpg)
The button is only visible when the sidebar is visible.

**Comment by KOT040188** [comment]
Yes, that's what I need! button, you can only do a little more, otherwise it will be difficult to get it =) Now I have no such button. So I can count on the creation of this buttons?

**Comment by luspi** [comment]
The new button takes its size from the same setting used for the exit button that is displayed on the main image. So if you adjust the size of the 'closing x' in the settings, this button will also be updated.

Yes, it is part of the code already: [commit](https://gitlab.com/luspi/photoqt/commit/da02949f4016f7b95a7a39981c5852b85bdc4c5a)
(The server seems to be back up and running again)

**Comment by KOT040188** [comment]
Thank you.
