### ISSUE TITLE
Several functions on one button

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#61]
I can assign to the keyboard or mouse button only one function. For example 'zoom to actual size' or 'Reset zoom'. It would be a good idea to appoint two these functions on one keyboard or mouse button. And they would act in turn. This behavior I've seen in other image viewer.

**Comment by luspi** [comment]
Hm, I'm not so sure about that... That can open a can of worms, like when assigning contradicting actions to the same shortcuts. A possible solution for that would be a list of actions that can work together (e.g., 'zoom in' and 'rotate left'). I'll add it to the roadmap to look into it a little more at a later time (though probably not before the next release)...

**Comment by KOT040188** [comment]
Я имел ввиду только эти две функции. Согласитесь, что их совместная работа на одной кнопке это очень удобно. Остальные функции мне не нужны на одной кнопке. Но эти две функции можно назначить на одну кнопку во многих просмотрщиках изображений. Я не думаю, что это сложно реализовать. Ещё раз повторю, что мне нужны только эти две функции на одной кнопке.
I meant only to these two functions. Agree that they work together on one button is very convenient. The rest of the features I do not need on a single button. But these two functions can be assigned to one button in many image viewer. I do not think it is difficult to implement. Once again, I only want these two functions in one button.

**Comment by luspi** [comment]
Oh, ok, I see. In theory it is not at all difficult to implement this. The difficulty is that my current implementation is based on the assumption that every shortcut is only used at most for one action. If there were two actions for the same shortcut, the first one would be overwritten by the second one and only the second one is executed.

**Comment by KOT040188** [comment]
I have an idea. I figured out how to set two functions to one button. Violate your principle of "one button = one function" is not necessary. It is necessary to create the dual function of the 'zoom to actual size/Reset zoom'. And the problem is solved! =)

**Comment by luspi** [comment]
Just a quick update: In the next version, it will be possible to set a shortcut for any amount of functions, the limitation of one button for one function will be gone!

**Comment by KOT040188** [comment]
It is very good.

**Comment by luspi** [comment]
New version released today, also updated in PPA for 16.04 and 17.10!
