### ISSUE TITLE
Drag the image left mouse button

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#62]
Я назначил функцию изменения масштаба на левую кнопку мыши. Когда я перетаскиваю изображение левой кнопкой мыши, срабатывает и назначенная на неё функция изменения масштаба. Это плохо. Исправьте пожалуйста.
I have appointed the zoom function on the left mouse button. When I drag the image with the left mouse button is activated and assigned to it a function of zoom. This is bad. Please correct.

**Comment by luspi** [comment]
The next release brings a completely redone shortcuts engine. This is one of the bugs that is fixed with that!

**Comment by KOT040188** [comment]
Thank you. And when will the next release?

**Comment by luspi** [comment]
I hoping soon! I'm currently working on the image engine, there's is one of the features that didn't work properly before that I'm trying to fix right now. It proofs to be a little tricky to do, but once that is done I'm only planning on a few minor improvements before I move to beta testing (for bug fixing and translations). I hope to be able to take this step within the next week or two. The beta testing will probably take another week or so... A guess for the next release would be that it is two to three weeks away.
