### ISSUE TITLE
Image scale.

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#63]
When you change the scale of the image, the scale is maintained until the end of viewing images and exit photoqt. Is it possible to add such an option, at which the scale will be reset to default when scrolling images.

**Comment by luspi** [comment]
You mean, setting PhotoQt to no remember the scale of an image when you switch to another image? This is actually the default behaviour. To change this setting, go into the settings manager, in the very first tab towards the bottom, you can disable/enable the feature to remember the current scale/zoom level.

**Comment by KOT040188** [comment]
Большое спасибо. Теперь всё в порядке. Настройки на английском, а я пока не знаю английского =)
