### ISSUE TITLE
photoqt is not closed after clicking the left mouse button on an empty place ￼

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#64]
I just updated photoqt and found a bug. When pressing the left mouse button on an empty area of photoqt is not closed. In the settings photoqt this item is selected. This item worked in a previous version of photoqt.

**Comment by luspi** [comment]
Thanks for letting me know! The fix was very easy (I forgot some redundant code), so I just updated the Ubuntu package including the fix. You should have it very soon now :-)

**Comment by KOT040188** [comment]
Thank you. Now everything is in order.
