### ISSUE TITLE
Scale images when you start photoqt

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#66]
I sometimes browse images that are smaller than my screen. When opened in photoqt, they are stretched to fill the screen. I don't need it. If you then scroll through images by mouse wheel, they are no longer stretched to full screen. I found no such settings in photoqt. I'm not sure, but I think that in older versions of photoqt did not stretch small images.

**Comment by luspi** [comment]
Oh, yes, you're right, this is a bug in the latest PhotoQt... I'll see what's going on and let you know how I get on! Thanks for reporting!

**Comment by luspi** [comment]
Just a quick update: This will be fixed in the next version. The next version is finally coming likely some time over the next two months (still some work to be done beforehand)...

**Comment by luspi** [comment]
New version released today including above mentioned fix, also updated in PPA for 16.04 and 17.10!
