### ISSUE TITLE
Function closing photoqt after pressing the left mouse button on an empty place is working bad

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#67]
Function closing  photoqt after pressing the left mouse button on an empty place works only in the top half of the screen. In the bottom half of the screen this feature does not work

**Comment by luspi** [comment]
Thanks for letting me know! I just pushed the change to fix this. The cause was due to a change in the animation of the thumbnails, causing a logical flaw in detecting whether they are visible or not...
