### ISSUE TITLE
When will the packages available for 17.10?

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt-legacy#68]
When will the packages available for 17.10?https://launchpad.net/~lumas/+archive/ubuntu/photoqt

**Comment by KOT040188** [comment]
Is anybody here?

**Comment by luspi** [comment]
Sorry, life circumstances didn't allow me to spend much (or any) time on PhotoQt recently... However, I did just now update launchpad with packages for Ubuntu 17.10
